"""Tests for the action_trib task (order-3 action family).

Sequence format: [x0, x1, x2, flag, x3, flag, x4, ...] where x_j is
generated by the rule named by its preceding flag. ACTION coefficient
convention (opposite of LinearRecurrenceRule): the first coefficient
multiplies the OLDEST value, i.e. x_j = (a*x_{j-3} + b*x_{j-2} + c*x_{j-1}) % p
for rule (a, b, c).
"""
import os
import random
import sys

import torch

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src'))

from datasets import BatchTag, ActionDataset, make_action_missing_collate
from experiment import _prepare_action

P, PAIRS, L = 7, [(1, 1, 1), (1, 2, 3)], 10


def _make(seed=42, n=200, length=L):
    return ActionDataset(p=P, ab_pairs=PAIRS, num_samples=n, length=length,
                         seed=seed, order=3)


def test_sequence_format():
    ds = _make()
    for seq, _ in ds.samples[:50]:
        s = seq.tolist()
        assert len(s) == 2 * L - 3  # 3 initial values + 2 tokens per generated value
        # initial values
        assert all(tok < P for tok in s[:3])
        # flags at odd indices >= 3, values at even indices >= 4
        for i, tok in enumerate(s):
            if i >= 3 and i % 2 == 1:
                assert P + 1 <= tok < P + 1 + len(PAIRS), f"bad flag at {i}: {tok}"
            elif i >= 4:
                assert tok < P, f"bad value at {i}: {tok}"


def test_rule_adherence():
    ds = _make(n=50)
    for seq, _ in ds.samples:
        s = seq.tolist()
        values = s[:3]
        for j in range(3, L):
            flag = s[2 * j - 3]
            rule_idx = flag - (P + 1)
            a, b, c = PAIRS[rule_idx]
            # action convention: a multiplies the OLDEST of the 3 previous values
            expect = (a * values[-3] + b * values[-2] + c * values[-1]) % P
            got = s[2 * j - 2]
            assert got == expect, \
                f"x_{j}: rule {PAIRS[rule_idx]} on {values[-3:]} -> {expect}, got {got}"
            values.append(got)


def test_loss_mask():
    ds = _make()
    for _, mask in ds.samples[:50]:
        assert mask.sum().item() == L - 3  # x3..x_L targets only
        for k in range(3, L):
            assert mask[2 * k - 3] == 1.0  # target idx of x_{k+1}: 2*(k+1)-3-2
        # flags and initial values never supervised
        for i in range(len(mask)):
            seq_idx = i + 1  # target i aligns with seq[i+1]
            if seq_idx < 3 or (seq_idx >= 3 and seq_idx % 2 == 1):
                assert mask[i] == 0.0


def test_corruption_flags_untouched():
    ds = _make()
    collate = make_action_missing_collate(p=P, missing_prob=0.5, miss_len=3, order=3)
    views, tag, cleans, masks = collate(ds.samples[:100])
    assert tag == BatchTag.ACTION_MISS
    n_masked = 0
    for view, clean in zip(views, cleans):
        v, c = view.tolist(), clean.tolist()
        for i, tok in enumerate(v):
            if i >= 3 and i % 2 == 1:
                assert tok >= P + 1, f"flag position {i} corrupted: {tok}"
            if tok == P:
                assert i >= 4 and i % 2 == 0, f"M at non-value position {i}"
                n_masked += 1
        for a, b in zip(v, c):
            assert a == b or a == P
    assert n_masked > 0


def test_prepare_wiring():
    cfg = {'main': {
        'P': P, 'D_MODEL': 16, 'N_HEAD': 1, 'N_LAYER': 1, 'BATCH_SIZE': 16,
        'DROPOUT': 0.0, 'ABC_PAIRS': [list(p) for p in PAIRS],
        'NUM_TRAIN_SAMPLES': 20, 'NUM_TEST_SAMPLES': 10,
        'TRAIN_LEN': 8, 'OOD_LEN': 10,
    }}
    random.seed(0)
    torch.manual_seed(0)
    ctx = _prepare_action(cfg, order=3)
    assert ctx['model'].vocab_size == P + 1 + len(PAIRS)
    assert ctx['model'].pad_token_id == P
    assert ctx['save_config']['order'] == 3
    assert ctx['save_config']['ab_pairs'] == PAIRS
    # block_size covers 2*OOD_LEN - 3 = 17 -> 32
    assert ctx['save_config']['block_size'] == 32
    seq, mask = ctx['train_dataset'][0]
    assert len(seq) == 2 * 8 - 3
    assert len(ctx['train_dataset']) == 20
    assert len(ctx['test_dataset']) == 10

    # Wrong coefficient count must raise.
    cfg['main']['ABC_PAIRS'] = [[1, 1], [1, 2]]
    try:
        _prepare_action(cfg, order=3)
        assert False, "2-coefficient rules under order=3 must raise"
    except ValueError:
        pass


def test_order2_regression_same_seed_same_samples():
    # The order-generalized code path must reproduce the legacy order-2
    # samples bit-for-bit (same rng call sequence, same recurrence).
    pairs2 = [(1, 1), (1, 2)]
    a = ActionDataset(p=P, ab_pairs=pairs2, num_samples=20, length=L, seed=7)
    b = ActionDataset(p=P, ab_pairs=pairs2, num_samples=20, length=L, seed=7, order=2)
    for (sa, ma), (sb, mb) in zip(a.samples, b.samples):
        assert sa.tolist() == sb.tolist()
        assert ma.tolist() == mb.tolist()


if __name__ == '__main__':
    test_sequence_format()
    test_rule_adherence()
    test_loss_mask()
    test_corruption_flags_untouched()
    test_prepare_wiring()
    test_order2_regression_same_seed_same_samples()
    print("ALL TESTS PASSED: test_action_trib.py")
